---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: content/mass-times
  label: Mass Times
- type: document
  path: content/donate.md
  label: Donate
- type: directory
  path: content/services
  label: Services
  create: all
  match: "**/*"
- type: directory
  path: content/resources
  label: Resources
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: Our Community
  create: all
  match: "**/*"
- type: directory
  path: content/news
  label: News & Events
  create: all
  match: "**/*"
- type: directory
  path: content/bulletin
  label: Bulletin
  create: all
  match: "**/*"
- type: document
  path: content/contact.md
  label: Contact
- type: document
  path: content/_index.md
  label: Home
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
